name: Docker Image CI

on:
  push:
    branches: [ python2 ]
  pull_request:
    branches: [ python2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dkorange/scrapy:$(date +%s)
